import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { getServerSession } from "next-auth";
import { authOptions } from "../server/auth";
import Providers from "./_components/providers";
import Header from "./_components/header";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={`${geist.variable} min-h-screen items-center justify-center bg-gradient-to-b from-primary to-[#15162c] text-white`}>
      <body>
        <Providers session={session}>
          <Header session={session} />
        </Providers>
        <Providers session={session}> {children}</Providers>
        <Toaster position="bottom-center" richColors className="bg-secondary" />
      </body>
    </html>
  );
}
